Домашнее задание 1
mashelll/2018-FS-11-Frontend-Komitsky pull request #1
Opened 2018-10-11 17:26 UTC by mashelll

* переписала функцию say, но пока получилось только на HTML, на CSS перепишу позже;
* интегрировала в сборку esLint (с конфигом airbnb), скрипт запуска напишу позже;

2018-10-13 08:54 UTC, martinkomitsky requested changes
исправить замечания, +:
1. Дописать скрипт запуска eslint
2. Запустить его и исправить ошибки, на которые он указывает (если уже не сделано)

2018-10-13 08:54 UTC, martinkomitsky commented on src/index.js~
> +say();
что это за файл такой?  `src/index.js~`

2018-10-13 08:54 UTC, martinkomitsky commented on src/index.js~
> +say();
нашел еще такой же `./lib/test.js~` - это какой-то мусор, надо удалить

2018-10-13 08:54 UTC, martinkomitsky commented on src/index.js~
> -//var div = document.createElement('div');
Потерялся файл `.css`, его надо тоже добавить в репозиторий.

2018-10-13 08:55 UTC, martinkomitsky commented
А еще, самое важное: если хочешь-таки получить за это ДЗ балл, то исправь мою фамилию в репозитории на свою, иначе оценку себе поставлю))

2018-10-15 10:53 UTC, martinkomitsky requested changes
![image](https://user-images.githubusercontent.com/14847018/46946552-c5ef8480-d080-11e8-9887-36801502a22e.png)
1. Питон в этом репозитории не нужен. Удали, пожалуйста, пожалей меня((
2. Скрипт запуска eslint - имелось ввиду внутри package.json. Можешь команду из своего sh скрипта перенести в `package.json.scripts.eslint`, а далее запускать через `npm run eslint`
3. https://github.com/mashelll/2018-FS-11-Frontend-Ermolaeva/blob/new_branch/src/lib/test.js Тут неправильно многое:
- Стили нужно вынести в отдельный css файл, в js использовать назначение css класса.
- Таблицу нужно создавать через [createElement](https://developer.mozilla.org/en-US/docs/Web/API/Document/createElement), а после этого добавлять в `body` через  [appendChild](https://developer.mozilla.org/en-US/docs/Web/API/Node/appendChild)
- Очевидно, что `appendChild` должен быть вместо `write`. Этот метод очень опасен и его не используют в разработке

2018-10-15 11:32 UTC, mashelll commented
1. Прошу прощения за питон, это недорозумение.
2. Проблема со скриптом, он прекрасно работал если его запускать с аргументом в виде файла который нужно проверить, а если писать вот так  "*.js" , выдает: "All of the files matching the glob pattern "*.js" are ignored." Предлагает проверить файл .eslintignore, но такого не было создано.

2018-10-15 20:27 UTC, martinkomitsky commented on package.json
> +    "eslint": "node ./node_modules/eslint/bin/eslint --fix *.js"
Тут нужно указать папку, то бишь, выйдет так:
` "eslint": "node ./node_modules/eslint/bin/eslint ./src --fix"`

2018-10-15 20:28 UTC, martinkomitsky commented on package.json~
> +  "name": "messager",
Этот файл тоже мусор, удалить

2018-10-15 20:28 UTC, martinkomitsky commented on script_eslint.sh
> +node ./node_modules/eslint/bin/eslint  --no-ignore *.js
Смело удаляй

2018-10-15 20:30 UTC, martinkomitsky requested changes
Ожидаю правки 2-3

2018-10-17 19:05 UTC, mashelll commented
Исправила как надо скрипт.
Линтер ругается на объект document в  text.js:  "'document' is not defined"  Это как то можно исправить?
Проблемы со сборкой вместе с CSS, все выходные разбиралась, исправила ряд возникших проблем, но все равно еще не до конца, насколько я поняла текущая проблема связана с конфликтом версий программ.

2018-10-17 19:25 UTC, martinkomitsky commented on src/lib/test.js
> +  document.write(`Hello, ${name}!`);
Кажется, я уже писал:
>Таблицу нужно создавать через createElement, а после этого добавлять в body через appendChild
Очевидно, что appendChild должен быть вместо write. Этот метод очень опасен и его не используют в разработке

2018-10-17 19:30 UTC, martinkomitsky requested changes
Правки:
1. Избавиться-таки уже от document.write
2. Для того, чтобы решить проблему с `document is undefined`, надо добавить в конфиг [линтера](https://github.com/mashelll/2018-FS-11-Frontend-Ermolaeva/blob/new_branch/.eslintrc.js) ключ:
```
"env": {
    "browser": true
  },
```
3. Css сейчас подключается через html, как отдельный файл. Это нормально, но если есть желание, как добавлять стили при помощи webpack, то можно обратиться к ответу https://stackoverflow.com/questions/44474484/how-to-import-css-files-into-webpack#

2018-10-18 14:16 UTC, martinkomitsky approved these changes

2018-10-18 14:17 UTC, merged

2018-10-18 14:17 UTC, martinkomitsky commented
`Finally` 10