Домашнее задание 2
mashelll/2018-FS-11-Frontend-Komitsky pull request #2
Opened 2018-10-25 16:39 UTC by mashelll

2018-10-30 19:40 UTC, martinkomitsky requested changes
Привет!
А тут не сделан последний пункт из задания про функцию `getReadableSize`:
https://github.com/mialinx/tt-fullstack/blob/master/1sem/front/lesson-2/homework.md

2018-11-06 13:21 UTC, martinkomitsky commented
@mashelll будет движение?

2018-11-07 16:35 UTC, mashelll commented
Да, будет. Пока завалы по учебе и по Backend-у, но я в процессе.

2018-11-08 09:55 UTC, martinkomitsky commented on src/app/create/index.html
> +	<script>
Во-первых, скрипты мы так больше не пишем.
Надо вынести в отдельный js модуль и там для этой функции написать `export`

2018-11-08 09:56 UTC, martinkomitsky commented on src/app/create/index.html
> +			while (size >= 1024) {
Зачем делать какой-то цикл? у тебя на вход этой функции приходит размер, его достаточно просто поделить и все. Посмотри самостоятельно, как сделали твои коллеги эту задачу

2018-11-08 09:57 UTC, martinkomitsky approved these changes
Необходимо исправить замечание в следующем дз

2018-11-08 09:57 UTC, merged

2018-11-08 09:57 UTC, martinkomitsky commented
После срока и замечания. 4